kind = "mobile"
previewPath = "/"
title = "Bonilla Tour's"
version = "1.0.0"
id = "artifacts/bonilla-tours"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 21770

[services.development]
run = "pnpm --filter @workspace/bonilla-tours run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/bonilla-tours", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/bonilla-tours", "run", "serve" ]

[services.env]
PORT = "21770"
BASE_PATH = "/"
